services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local-aftermint
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - lambda-local
  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-node-aftermint
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"
    command:
      dynamodb describe-limits --endpoint-url http://dynamodb-local-aftermint:8000 --region us-east-1
    networks:
      - lambda-local
networks:
  lambda-local:
    external: true